import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import AddPostBtn from "@/components/AddPostBtn";
import Footer from "@/components/Footer";
import { Toaster } from "sonner";
import useUser from "@/hooks/useUser";
import { createContext } from "react";
import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = useUser();

  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster richColors />
        <Navbar></Navbar>
        <Providers user={user}>{children}</Providers>
      </body>
    </html>
  );
}

export const dynamic = "auto";
export const dynamicParams = true;
export const revalidate = false;
export const fetchCache = "auto";
export const runtime = "nodejs";
export const preferredRegion = "auto";
export const maxDuration = 5;
