name: Deploy static content to Pages

on:
  push:
    branches: ["main", "userProfile"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Single deploy job since we're just deploying
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
